---
title: "01_presentation_batches"
format: html
editor: source
---

```{r}
#| echo: false

targets::tar_config_set(store = "outputs/pipeline/", 
                        script = "analyses/pipeline.R")

```

## Est-ce que toutes les chromatos sont présentes
 Année 2023
```{r}
#| echo: false
#| label: 'tbl-chromato_2023'
#| fig-cap: "Table de présence dans le cloud des chromato pour l'année 2023"
targets::tar_load(check_chromato_2023)

kableExtra::kbl(check_chromato_2023) |> 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

```{r}
#| echo: false
#| label: 'tbl-chromato_2024'
#| fig-cap: "Table de présence dans le cloud des chromato pour l'année 2024"
targets::tar_load(check_chromato_2024)

kableExtra::kbl(check_chromato_2024) |> 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```
```{r}
#| echo: false
#| label: 'tbl-chromato_2025'
#| fig-cap: "Table de présence dans le cloud des chromato pour l'année 2024"
targets::tar_load(check_chromato_2025)

kableExtra::kbl(check_chromato_2025) |> 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

En résumé pour les chromatos de 2023 il y a tous les tubes "composé C5" sauf B_198952_15062023 puisque HS, est-ce qu'à la place on pourrait utilisé l'échantillon C5 ? 

Pour l'année 2024 il manque : `r paste(unique(check_chromato_2024$missing_list), collapse = ", ")` 
```{r}
#| echo: false
#| layout-ncol: 2
#| label: 'fig-chrono_chromato'
#| fig-cap: "Date des batches de désorbtion pour l'année 2023 et 2024"
#| fig-subcap: 
#|  - "2023"
#|  - "2024"
#| warning: false 
targets::tar_load(chronologie_2023)
chronologie_2023
targets::tar_load(chronologie_2024)
chronologie_2024

```


Pour l'année 2024 il manque : `r paste(unique(check_chromato_2024$missing_list), collapse = ", ")`

